services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring
    ports:
      - "9091:9091"

  grafana:
    image: grafana/grafana
    networks:
      - monitoring
    ports:
      - "3000:3000"

networks:
  monitoring:
    driver: bridge
